name: Workflow B
on: push

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Before
        run: echo "..."
      - name: Sleep
        run: sleep 60
      - name: After
        run: echo "done"
