name: Test callee
on:
  workflow_call:

jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env
      - name: Event data
        run: cat $GITHUB_EVENT_PATH
