name: Matrix
on:
  push:
    branches:
      - '🙄'

permissions:
  actions: read
  contents: read

jobs:
#  build:
#    name: Build git
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#          sudo sed -i -e 's/Types: deb/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
#
#          sudo apt-get update
#          sudo apt-get build-dep git
#          git clone --depth=1 --branch=v2.53.0 https://github.com/git/git
#          cd git
#          make
#      - uses: actions/upload-artifact@v7
#        with:
#          name: git
#          path: git/git
#          retention-days: 1

  test:
    name: Test git deepen ${{ matrix.n }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
#    needs: [ build ]
    strategy:
      matrix:
        n: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
    steps:
#      - uses: actions/download-artifact@v7
#        with:
#          name: git
      - uses: actions/checkout@v6
      - run: |
          unzip git.zip
          chmod +x git
          rm -rf .git

          function git {
            printf '\e[32mgit'
            printf ' %q' "$@"
            printf '\e[0m\n'
            ./git "$@"
          }

          git --version
          git init .
          git remote add origin https://github.com/Automattic/jetpack
          git config --local gc.auto 0
          git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=10 origin 57a055c07d944301558ce5727f803ee427abd15d
          git sparse-checkout disable
          git config --local --unset-all extensions.worktreeConfig
          git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=10 origin 57a055c07d944301558ce5727f803ee427abd15d 77c13651933aedae78b1f6a2e3e0cef84943d2a3
          echo "---"
          stat .git/shallow
          cat .git/shallow
          echo "---"
          EXIT=0
          if ! git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=20 origin 57a055c07d944301558ce5727f803ee427abd15d 77c13651933aedae78b1f6a2e3e0cef84943d2a3; then
            EXIT=1
          fi
          echo "---"
          stat .git/shallow
          cat .git/shallow
          exit $EXIT
