name: Pnpm test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b
        with:
          version: 11.25.0
          runtime: node@24.15.0
          install: false
      - run: git diff
