name: Pnpm test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b
      - run: git diff
