name: Renovate
on:
  push:

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/renovate-cache.tar.xz
          key: ${{ runner.os }}-renovate3
          restore-keys: |
            ${{ runner.os }}-renovate3
      - if: steps.cache.outputs.cache-hit
        run: |
          if [[ -f /tmp/renovate-cache.tar.xz ]]; then
            docker run --volume /tmp:/tmp --user 1000:$(getent group docker | awk -F: '{print $3}') --rm --workdir /tmp renovate/renovate:32.0.3-slim tar --xz -xvvf renovate-cache.tar.xz
          fi
      - uses: renovatebot/github-action@v32.0.3
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_DRY_RUN: true
      - run: |
          if [[ -d /tmp/renovate/cache ]]; then
            rm -f /tmp/renovate-cache.tar.xz
            docker run --volume /tmp:/tmp --user 1000:$(getent group docker | awk -F: '{print $3}') --rm --workdir /tmp renovate/renovate:32.0.3-slim tar --xz -cvvf renovate-cache.tar.xz renovate/cache
          fi
