name: Renovate
on:
  push:

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /tmp/renovate/cache
          key: ${{ runner.os }}-renovate
          restore-keys: |
            ${{ runner.os }}-renovate
      - uses: renovatebot/github-action@v32.0.3
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
          # Remove this before merging too.
          RENOVATE_DRY_RUN: true
