name: Scheduled run 1
on:
  schedule:
    - cron: '* * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    env:
      FOO: ${{ github.event.inputs.dryRun == 'no' && 'null' || github.event.inputs.dryRun || 'null' }}
    steps:
      - run: |
          echo "ok: $FOO"
