name: Test permissions
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Check tags (1)"
          git ls-remote --tags origin autorelease_kill_switch
          echo "Check tags (2)"
          git ls-remote --tags origin permissions-test

          echo "Create release"
          git archive -v --output="slug.zip" --prefix="slug/" HEAD
          gh release create "create-release-test" slug.zip --notes "These are the notes" --target "$GITHUB_SHA" --title "Test release"

          echo "List releases"
          gh release list --limit 100 --json tagName --jq '.[].tagName | select( contains( "test" ) )'

          echo "Delete release"
          gh release delete "create-release-test" --cleanup-tag --yes
