name: Test tag matching
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+.[0-9]+'

jobs:
  job:
    name: Test tag matching
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_REF"
