name: Test label event
on:
  pull_request:
    types: [ labeled, unlabeled ]
  workflow_dispatch:

jobs:
  job:
    name: Job
    runs-on: ubuntu-latest
    steps:
      - name: Info
        env:
          EVENT: ${{ toJson( github ) }}
        run: jq . <<<"$EVENT"
