name: Concurrency test

on:
  workflow_dispatch:

concurrency:
  group: foobar-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  a:
    name: A
    runs-on: ubuntu-latest
    concurrency:
      group: xyz
      cancel-in-progress: true
    steps:
      - run: sleep 120
  b:
    name: B
    runs-on: ubuntu-latest
    concurrency:
      group: xyz
      cancel-in-progress: true
    steps:
      - run: sleep 120
  c:
    name: C
    runs-on: ubuntu-latest
    concurrency:
      group: xxx-${{ github.run_id }}
    steps:
      - run: sleep 120
