name: Reusable workflow callee
on:
  workflow_call:

jobs:
  thejob:
    name: Generate artifact
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello" > test.txt
      - uses: actions/upload-artifact@v7
        with:
          path: test.txt
          retention-days: 1
          compression-level: 0
          archive: false

  otherjob:
    name: Other job
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: exit 1
