name: Test PHP
on:
  push:

jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          while command -v php 2>/dev/null ]]; do
            rm -v "$(command -v php)"
          done
