name: Test delete
on:
  delete:
    branches: [ 'deleteme' ]

jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env
      - name: Event data
        env:
          DATA: ${{ toJson( github ) }}
        run: echo $DATA
