name: Concurrency test
on:
  workflow_dispatch:
    inputs:
      delay:
        description: Job delay
        required: true
        type: number
        default: 60

env:
  DELAY: ${{ inputs.delay }}

jobs:
  a:
    name: A
    runs-on: ubuntu-latest
    steps:
      - run: sleep "$DELAY"
  b:
    name: B
    needs: [ a ]
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10
  c:
    name: C
    needs: [ b ]
    runs-on: ubuntu-latest
    concurrency:
      group: test
      queue: max
    steps:
      - run: sleep 10
