name: Concurrency test
on:
  workflow_dispatch:
    inputs:
      workflowgroup:
        description: Group for the workflow
        type: choice
        default: none
        options:
          - a
          - b
          - none
      jobgroup:
        description: Group for the job
        type: string

concurrency:
  group: ${{ case( inputs.workflowgroup == 'none', github.run_id, inputs.workflowgroup ) }}
  cancel-in-progress: true

jobs:
  thejob:
    name: The job; workflowgroup=${{ inputs.workflowgroup }} jobgroup=${{ inputs.jobgroup }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.jobgroup }}
      queue: max
    steps:
      - run: sleep 300
