name: Test workflow_run
  
on:
  workflow_run:
    workflows: "Status test"
    types: [ 'requested' ]

jobs:
  dump:
    name: Dump target
    runs-on: ubuntu-latest

    steps:
      - name: Env
        run: env
      - name: github context
        run: |
          cat <<-EOF
          ${{ toJson(github) }}
          EOF
