name: Workflow Run test
on:
  workflow_run:
    types: [ 'completed' ]
    workflows:
      - Test
    branches: [ '🙄' ]

jobs:
  job:
    name: Dump
    runs-on: ubuntu-latest

    steps:
      - name: Dump
        run: jq -n --slurpfile event "$GITHUB_EVENT_PATH" '$event'

      - name: Message
        id: message
        run: |
          echo -n "::set-output name=message::"
          jq -nc --slurpfile event "$GITHUB_EVENT_PATH" '$event[0] as $e | {
            icon_emoji: ":test_tube:",
            blocks: [
              {
                type: "section",
                text: {
                  type: "mrkdwn",
                  text: "Test"
                }
              }
            ]
          }'

      - name: Slack test
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}
          payload: ${{ steps.message.outputs.message }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
