name: Run
on:
  workflow_run:
    types: [ 'completed' ]
    workflows:
      - Test

jobs:
  test:
    name: Check run?
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'

    steps:
      - name: Env
        run: env
      - name: Event data
        run: cat $GITHUB_EVENT_PATH
      - name: Check run?
        env:
          TOKEN: ${{ github.token }}
          SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          curl -v -X POST \
            --header "authorization: token $TOKEN" \
            --url https://api.github.com/repos/anomiex/testing/check-runs \
            --data "$(jq --arg sha "$SHA" --arg url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" -n '{
              "name": "Test check run",
              "head_sha": $sha,
              "details_url": $url,
              "status": "in_progress",
              "started_at": now | todateiso8601,
            }')"

