name: Run
on:
  workflow_run:
    types: [ 'completed' ]
    workflows:
      - Test

jobs:
  test:
    name: Check run?
    runs-on: ubuntu-latest

    steps:
      - name: Env
        run: env
      - name: Event data
        run: cat $GITHUB_EVENT_PATH
