name: Run 2
run-name: ${{ github.event.workflow.name }} on ${{ github.event.workflow_run.head_branch }}
on:
  workflow_run:
    types: [ 'completed' ]
    workflows:
      - Run

jobs:
  test:
    name: Check run?
    runs-on: ubuntu-latest

    steps:
      - name: Env
        run: env
      - name: Event data
        run: cat $GITHUB_EVENT_PATH
